# Generated by Django 6.0.2 on 2026-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_messages',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
