# Generated by Django 6.0.4 on 2026-04-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_alter_user_messages_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_messages',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_messages',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
