# Generated by Django 5.2.13 on 2026-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_alter_user_messages_body_alter_user_messages_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_messages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
